Route:
  - ipaas_framework.route.core.composite_router.CompositeRouter
  - ipaas_framework.route.core.simple_router.SimpleRouter

Operate:
  - ipaas_framework.operate.lambda_connector.LambdaConnector
  - ipaas_framework.operate.http_component.HTTPComponent
  - ipaas_framework.operate.sqs_connector.SQSConnector
  - ipaas_framework.operate.dynamodb_connector.DynamoDBConnector

Transform:
  - ipaas_framework.transform.jmespath_transformer.JMESPathTransformer
  - ipaas_framework.transform.handlebars_transformer.HandlebarsTransformer
